### ISSUE TITLE
Bot stops working 

### ISSUE THREAD

**Issue by ashifalimollick** [gabog/AzureServiceBusBotRelay#5]
Hi,
I followed all the steps and implemented the above solution.
After updating the message end point url in azure bot settings i run both the Azure Service Bot relay and my local bot. When i test it using webchat, the debugger point in my local host code is hit however my bot code does not work anymore. I get the send again retry option below my message which i sent to the bot. Upon checking my channels in azure i found the error was " There was an error sending this message to your bot: HTTP status code Forbidden".
How do i resolve this? i have followed the instructions in readme properly. Is it a bug of Azure relay?

**Comment by gabog** [comment]
Hi, did you configure the MicrosoftAppId and Password for your bot in appsettings.json or launchsettings.json? 

In the Emulator you can debug a bot without the appId and password but with the relay, you always need to have it in appsettings (similar to what you would do with ngrock.

**Comment by gabog** [comment]
Hi @ashifalimollick, I am closing this one, let me know if you are still having issues.

Gabo
