### ISSUE TITLE
.NET Core exe can't be referenced from a different folder

### ISSUE THREAD

**Issue by RAHarris** [gabog/AzureServiceBusBotRelay#6]
The project relies on Directory.GetCurrentDirectory() to reference the appsettings file, which will return the wrong value if the exe is invoked from a different directory. Something like this:
```
> "..\bots\proxy\ServiceBusRelayUtilNetCore.exe"
```
will fail to run because Directory.GetCurrentDirectory() will return the path of the current user, not `proxy`, and so can't find the appsettings file. Instead the base path should be generated with AppDomain.CurrentDomain.BaseDirectory.

More background here: https://github.com/dotnet/project-system/issues/3619

**Comment by gabog** [comment]
Thanks for the suggestion @RAHarris!, I merged your changes into master .
